name: Deploy to lambda
on: [push]
jobs:
  deploy:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build
      run: npm ci && npm run build && zip -r output.zip .
    - name: AWS Lambda Deploy
      if: github.ref == 'refs/heads/main'
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: ${{ secrets.AWS_LAMBDA_NAME }}
        zip_file: output.zip
        dry_run: true